# Sử dụng Node.js bản chính thức
FROM node:20

# Set thư mục làm việc trong container
WORKDIR /app

# Copy toàn bộ source code vào container
COPY . .

# Cài đặt các dependency
RUN npm install

# Biên dịch TypeScript sang JavaScript
RUN npm run build

# Chạy ứng dụng NestJS
CMD ["npm", "run", "start:prod"]
