version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: secure-auth-mongo
    restart: always
    environment:
      MONGO_INITDB_DATABASE: secure-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ../backend
    container_name: secure-auth-backend
    restart: always
    env_file:
      - ../backend/.env
    environment:
      - MONGO_URI=mongodb://mongodb:27017/secure-auth
      - PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
    command: >
      sh -c "npm install && npm run start:prod"

volumes:
  mongo_data: